export const productsTypes = {
    FETCH_PRODUCTS_START:'FETCH_PRODUCTS_START',
    SET_PRODUCTS_START:'SET_PRODUCTS_START',
    FETCH_PRODUCT_START:'FETCH_PRODUCT_START',
    SET_PRODUCT_START:'SET_PRODUCT_START'
}